Create Random_Forest.py
STAC-IITMandi/Exoplanet-Hunt pull request #3
Opened 2020-01-28 07:16 UTC by jahnvigupta

2020-01-31 12:48 UTC, ghost approved these changes

2020-02-05 09:20 UTC, shreyasbapat commented
As the PR seems quite unattended, I will take it for here. 

@jahnvigupta ,would you mind describing what exactly are you trying to do here? I am not in touch so!

2020-02-05 09:31 UTC, jahnvigupta commented
I have trained the model using random forest and calculated the accuracy on test data which came out to be .99 .

2020-02-05 09:43 UTC, shreyasbapat commented
Alright I am a bit skeptical about the results. Do you need me to merge the Pull Request?

2020-02-05 09:46 UTC, shreyasbapat requested changes
I suggest you to install :

`pip install isort black`

And then run:

`black Random_Forest.py`

and 

`isort Random_Forest.py` 

And then, the code would be much more readable!

2020-02-05 09:46 UTC, shreyasbapat commented on Random_Forest.py
> +from sklearn.ensemble import RandomForestClassifier
Alright, general practice, put all the imports up above the code.

2020-02-05 09:46 UTC, shreyasbapat commented on Random_Forest.py
> +data = pd.read_csv("train") #train is location of training data
Put this down somewhere.

2020-02-05 09:46 UTC, shreyasbapat commented on Random_Forest.py
> +model = model = RandomForestClassifier(n_estimators=100,
Typo here!

2020-02-05 09:47 UTC, shreyasbapat commented
Oh, and one more piece of advice, never and I repeat **never** use `master` branch to create merge requests! 
Always create a new branch every time you want to make new changes.

2020-04-03 17:27 UTC, lalitnarayanmudgal commented
@jahnvigupta are  you still working on this?

2020-04-26 03:23 UTC, abhijeetmanhas commented
@jahnvigupta can you update the PR according to recent template?

2020-11-29 13:05 UTC, LalitNM commented
I am merging this as this doesn't have a conflict. I am going to rearrange some files in repository ([this](https://github.com/STAC-IITMandi/Exoplanet-Hunt/blob/master/Bishop%20-%20Pattern%20Recognition%20And%20Machine%20Learning%20-%20Springer%20%202006.pdf) and [this](https://github.com/STAC-IITMandi/Exoplanet-Hunt/blob/master/duda-etal-00.pdf) should be in a separate directory, maybe in `/docs`).

2020-11-29 13:05 UTC, merged